### ISSUE TITLE
Extraction failed: not an lzma file 0.6.2

### ISSUE THREAD

**Issue by RobinFrcd** [lutris/dxvk-nvapi#4]
Hi,
Lutris won't boot anymore because of the latest release. Is there something wrong with the packaging ?

https://github.com/lutris/dxvk-nvapi/releases/tag/v0.6.2

```
DEBUG    2023-03-18 16:57:03,312 [lutriswindow.update_store:448]:Showing 2 games
DEBUG    2023-03-18 16:57:03,319 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-03-18 16:57:03,415 [http.write_to_file:142]:Writing to /home/robz/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
INFO     2023-03-18 16:57:03,418 [dll_manager.upgrade:244]:Downloading DXVK-NVAPI v0.6.2...
INFO     2023-03-18 16:57:03,420 [dll_manager.download:126]:Downloading https://github.com/lutris/dxvk-nvapi/releases/download/v0.6.2/dxvk-nvapi-v0.6.2.tar.xz to /home/robz/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz
DEBUG    2023-03-18 16:57:03,421 [http._request:88]:GET https://github.com/lutris/dxvk-nvapi/releases/download/v0.6.2/dxvk-nvapi-v0.6.2.tar.xz
DEBUG    2023-03-18 16:57:03,664 [http.write_to_file:142]:Writing to /home/robz/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz
INFO     2023-03-18 16:57:03,668 [dll_manager.download:131]:Extracting /home/robz/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz to /home/robz/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/v0.6.2
DEBUG    2023-03-18 16:57:03,669 [extract.extract_archive:127]:Extracting /home/robz/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz to /home/robz/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/v0.6.2
ERROR    2023-03-18 16:57:03,669 [extract.extract_archive:138]:Extraction failed: not an lzma file
ERROR    2023-03-18 16:57:03,669 [jobs.target:36]:Error while completing task <bound method StartupRuntimeUpdater.update_runtimes of <lutris.startup.StartupRuntimeUpdater object at 0x7f891855dff0>>: <class 'lutris.util.extract.ExtractFailure'> not an lzma file
  File "/app/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/lutris/startup.py", line 206, in update_runtimes
    dll_manager.upgrade()
  File "/app/lib/python3.10/site-packages/lutris/util/wine/dll_manager.py", line 245, in upgrade
    self.download()
  File "/app/lib/python3.10/site-packages/lutris/util/wine/dll_manager.py", line 132, in download
    extract_archive(archive_path, self.path, merge_single=True)
  File "/app/lib/python3.10/site-packages/lutris/util/extract.py", line 139, in extract_archive
    raise ExtractFailure(str(ex)) from ex
```

cc @GloriousEggroll

**Comment by Reonaydo** [comment]
Last archive is gzip file, not lzma(xz)
```
~ $ file /tmp/dxvk-nvapi-v0.6.2.tar.xz 
/tmp/dxvk-nvapi-v0.6.2.tar.xz: gzip compressed data, from Unix, original size modulo 2^32 8437760
```

**Comment by TocNoc** [comment]
Just confirming that manually extracting the file dxvk-nvapi-v0.6.2.tar.xz to it's own folder fixed Lutris and games initialization.

**Comment by DonneyOne** [comment]
Hello guys,

Just to mention it for the people that want a quick fix that the 0.5.4 release is very stable.

Changing ln 111 -> return re.sub("0\.6\.2", "0.5.4", release["assets"][0]["browser_download_url"] in /lutris/util/wine/dll_manager.py fixed it for me even though it is a hard-coded solution.

That was the best I could do in the middle of a game with 3 error msgs/statuses :D 

Have a nice one lads.

**Comment by rydymth** [comment]
> Just confirming that manually extracting the file dxvk-nvapi-v0.6.2.tar.xz to it's own folder fixed Lutris and games initialization.

Yes this works! Just make sure to disconnect from internet when starting lutris/starting game otherwise for me it started to download the new dxvk-nvapi again and the same errors occured

**Comment by esiqveland** [comment]
I think the published package is just packaged wrongly with gzip instead of lzma.

**Comment by danieljohnson2** [comment]
You're right; that's what it is. If it were named .tar.gz Lutris could decompress it.

**Comment by MichalJe1985** [comment]
one simple update can broke entire program. nice.. very nice lutris

**Comment by danieljohnson2** [comment]
Not so. Lutris still works, it just whines every time you start it up.

It can't upgrade to the new version, but it should still be able to download an old one if you select one in the settings.

**Comment by MichalJe1985** [comment]
no. my every games on lutris stop working

**Comment by danieljohnson2** [comment]
What happens? Have you switched to an older DXVK-NVAPI version?

**Comment by MichalJe1985** [comment]
how i can do that?

**Comment by pumkinfield** [comment]
Ye, can confirm, not a single game works

**Comment by danieljohnson2** [comment]
Click on the 'configure' button next to 'Wine' in your sidebar; the right-most icon.  Turn on 'advanced' settings, go to 'Runner options', use the 'DXVK-NVAPI version' dropdown.

**Comment by MichalJe1985** [comment]
Now works, thanks!

**Comment by MichalJe1985** [comment]
still dont work. eh

**Comment by danieljohnson2** [comment]
So what happens instead of it working?

**Comment by MichalJe1985** [comment]
thanks for trying, but i hate that. i just uninstal lutris, fck that

**Comment by danieljohnson2** [comment]
Well, if you hate me trying, I guess that's it then.

**Comment by MichalJe1985** [comment]
I just hate looking for a solution for hours in linux.. I'll just stick with steam games. This is idiotic, i have lutris one day, and just 30 minutes ago stop working. It is not normal you know

**Comment by frafall** [comment]
Well, Lutris insists on downloading at start of client and game, so even though I unpack/repack it will overwrite and fail. Trying to make file immutable results in error when lutris tries to update... :( 

Have not found any way to skip the update process so its "game over" until corrupt file is repacked/replaced

**Comment by GloriousEggroll** [comment]
fixed, duplicate  of https://github.com/lutris/lutris/issues/3386
